apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
  labels:
    app.kubernetes.io/name: hello
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name:  hello